version: '3.8'

services:
    nginx:
        image: nginx:1.17.4
        container_name: nginx
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./docker_settings/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker_settings/logs:/var/log/nginx
            - ./:/var/www/html
        depends_on:
            - php
        networks:
            - app-network

    php:
        build:
            context: ./docker_settings
            dockerfile: Dockerfile_php81
        container_name: php
        volumes:
            - ./../:/var/www/html
            - ./php.ini:/usr/local/etc/php/conf.d/php-memory-limit.ini
        networks:
            - app-network

    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: Europe/Budapest
            LANG: C.UTF_8
            MYSQL_CHARSET: utf8mb4
            MYSQL_COLLATION: utf8mb4_unicode_ci
        ports:
            - "33063:3306"
        volumes:
            - ./docker_settings/mysql_data:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "${PHPMYADMIN_PORT}:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: ${DB_USER}
            PMA_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 1000M
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql_data:
